### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [sudheer-ranga/aliexpress-product-scraper#11]
Can i get prices of item when ship is for example only from Poland?

**Comment by marcinkowalczyk2** [comment]
for example: const product = scrape('1005001769545853', [PL])
and this show me only prices of item when ship is from poland

**Comment by sudheer-keastone** [comment]
This particular product is not showing prices apart from China. Other locations are not delivering and so it is not showing the prices.
