### ISSUE TITLE
Review limiter

### ISSUE THREAD

**Issue by akshaycj** [sudheer-ranga/aliexpress-product-scraper#12]
Why is there a limit for review fetching? like 10 pages or 100 reviews?

**Comment by akshaycj** [comment]
is that number kept fixed so that aliexpress doesn't block the requests? or can I go ahead and increase that?

**Comment by sudheer-ranga** [comment]
You can increase the limit by modifying the source. I have released a new release v2.0.2. When you are using scrapers and doing some heavy work, make sure you use proxies so that aliexpress won't block the scripts.
